### ISSUE TITLE
aria-checked support?

### ISSUE THREAD

**Issue by gordonbisnor** [tesk9/accessible-html#9]
@tesk9 First of all thank you for creating this awesome library and your talk about it, which provided a great intro!

I am trying to implement nicer looking checkboxes and have realized that they are not a11y-friendly, trying to fix that up. 

The checkBox role and labelledBy in this library has me part of the way there. But the checkbox state is being read wrong. 

So now I'm looking at the aria-checked attribute, for which I see no support here. 

Is this something I might be able to pitch in and PR to add, or is there are a philosophical reason you did not include? or etc...

**Comment by tesk9** [comment]
Hi! Thanks for the question.

The [`checked` helper](http://package.elm-lang.org/packages/tesk9/accessible-html/3.1.0/Accessibility-Widget#checked) is in the Widget section of the library.

This makes me think I should make the documentation more explicit about what Attribute is actually produced. Thanks for bringing it up!

**Comment by gordonbisnor** [comment]
@tesk9  I think I was searching the module docs thinking it was searching the whole library! Thanks for the quick response!
